// session-demos/07-angular/awesome-store/src/app/app.component.ts
import { Component } from '@angular/core';
//import './xyz.css';

@Component(
    {
        selector: 'app-root',
        templateUrl: './app.component.html',
        styleUrls: ['./app.component.css']
    }
)
export class AppComponent {
    title: string = 'Awesome Store';
    counter: number = 0;

    constructor() {
        setInterval( () => this.counter++, 1000 );
    }
}

/*
1. Components (custom HTML tags)
2. Services - Business logic shared across the app
3. Pipes - transform data
4. Routing
5. Modules
*/
<div>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
        <a class="navbar-brand" routerLink="/">Amazin</a>
        <button class="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
            aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="collapsibleNavId">
            <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
                <li class="nav-item active">
                    <a class="nav-link" routerLink="/products">Products <span class="sr-only">(current)</span></a>
                </li>
            </ul>
        </div>
    </nav>
</div>

<router-outlet></router-outlet>

// supplied-files/src/components/App.jsx
import React from 'react';

import { Link, Route } from 'react-router-dom';
import About from './About';
import ProductListContainer from '../containers/ProductsList';
import ProductDetail from './ProductDetail';

import 'bootstrap/dist/css/bootstrap.min.css';

function App( props ) {
    return (
        <div>
            <nav className="navbar navbar-expand-sm navbar-light bg-light">
                <Link className="navbar-brand" to="/">Home</Link>
                <button className="navbar-toggler d-lg-none" type="button" data-toggle="collapse" data-target="#collapsibleNavId" aria-controls="collapsibleNavId"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span className="navbar-toggler-icon"></span>
                </button>
                <div className="collapse navbar-collapse" id="collapsibleNavId">
                    <ul className="navbar-nav mr-auto mt-2 mt-lg-0">
                        <li className="nav-item active">
                            <Link className="nav-link" to="/products">Products <span className="sr-only">(current)</span></Link>
                        </li>
                    </ul>
                </div>
            </nav>

            <Route path="/" component={About} exact={true} />
            <Route path="/products" component={ProductListContainer} exact={true} />
            <Route path="/products/:id" component={ProductDetail} exact={true} />
        </div>
    );
}

export default App;
